version: "3.8"
services:

  app-ktor:
    image: ktor-monitoring:latest
    restart: always
    ports:
      - "3800:3800"

  app-micronaut:
    image: micronaut-monitoring:latest
    restart: always
    ports:
      - "3802:3802"

  app-spring-boot:
    image: spring-boot-monitoring:latest
    restart: always
    ports:
      - "3801:3801"

  app-spring-boot-kt:
    image: spring-boot-kotlin-monitoring:latest
    restart: always
    ports:
      - "3804:3804"

  app-quarkus-java:
    image: quarkus-java-monitoring:latest
    restart: always
    ports:
      - "3803:3803"

  prometheus:
    image: prom/prometheus:v2.33.3
    restart: always
    ports:
      - "3500:9090"
    volumes:
      - ./monitoring:/etc/prometheus/
    links:
      - app-ktor
      - app-micronaut
      - app-spring-boot
      - app-spring-boot-kt
      - app-quarkus-java

  grafana:
    image: grafana/grafana-oss:8.5.0-51645pre-ubuntu
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - app-ktor
      - app-micronaut
      - app-spring-boot
      - app-spring-boot-kt
      - app-quarkus-java
      - prometheus
