micronaut:
  application:
    name: micronaut-monitoring
  server:
    port: 3805
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
endpoints:
  metrics:
    enabled: false
    sensitive: false
netty:
  default:
    allocator:
      max-order: 3
