{
 "title": "JVM GC",
 "description": "JVM GC collection.",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Heap Utilization",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{job=\"$job\"})",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Pressure",
   "type": "graph",
   "description": "Triggers when the heap usage after major GC crossed the threshold.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{job=\"$job\"}",
     "legendFormat": "Size of Old Gen after last GC"
    },
    {
     "expr": "jvm_gc_max_data_size_bytes{job=\"$job\"}",
     "legendFormat": "Max size of Old Gen pool"
    },
    {
     "expr": "jvm_gc_live_data_size_bytes{job=\"$job\"}/jvm_gc_max_data_size_bytes{job=\"$job\"}",
     "legendFormat": "Heap pressure"
    }
   ]
  },
  {
   "title": "Allocation and Promotion rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_memory_allocated_bytes_total{job=\"$job\"}[1m])",
     "legendFormat": "allocation rate"
    },
    {
     "expr": "rate(jvm_gc_memory_promoted_bytes_total{job=\"$job\"}[1m])",
     "legendFormat": "promotion rate"
    }
   ]
  },
  {
   "title": "Time Spent in GC by Cause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percent", "label": "percent of time" }
   ],
   "targets": [
    {
     "expr": "avg(rate(jvm_gc_pause_seconds_sum{job=\"$job\"}[1m])) by (cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Average GC Pause/time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(jvm_gc_pause_seconds_sum{job=\"$job\"}[1m])/rate(jvm_gc_pause_seconds_count{job=\"$job\"}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Max GC Pause Time by Cause",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(jvm_gc_pause_seconds_max{job=\"$job\"}) by (cause)",
     "legendFormat": "{{cause}}"
    }
   ]
  },
  {
   "title": "Live Data Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_live_data_size_bytes{job=\"$job\"}",
     "legendFormat": "live"
    },
    {
     "expr": "jvm_gc_max_data_size_bytes{job=\"$job\"}",
     "legendFormat": "max"
    },
    {
     "expr": "jvm_gc_live_data_size_bytes{job=\"$job\"} / jvm_gc_max_data_size_bytes{job=\"$job\"}",
     "legendFormat": "used"
    }
   ]
  }
 ]
}