{
 "title": "FW-Monitoring-Experiences",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "used"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{job=\"$job\", area=\"heap\"})",
     "legendFormat": "commited"
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_usage{job=\"$job\"}[1m])*100",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Java-Server-Request-GET",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{job=\"micronaut-monitoring\", method=\"GET\", uri!=\"/metrics\"})",
     "legendFormat": "micronaut-java"
    },
    {
     "expr": "sum( http_server_requests_seconds_count{job=\"spring-boot-monitoring\", method=\"GET\", uri!=\"/metrics\"})",
     "legendFormat": "spring-java"
    },
    {
     "expr": "sum( http_server_requests_seconds_count{job=\"quarkus-java-monitoring\", method=\"GET\", uri!=\"/metrics\"})",
     "legendFormat": "quarkus-java"
    },
    {
     "expr": "sum( ktor_http_server_requests_seconds_count{job=\"ktor-monitoring\", method=\"GET\", uri!=\"/metrics\"})",
     "legendFormat": "ktor-kotlin"
    }
   ]
  },
  {
   "title": "Java-Http-Total-Requests and Error (per sec),",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum( increase( http_server_requests_seconds_count{job=\"$job\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "Total Request"
    },
    {
     "expr": "sum ( increase(http_server_requests_seconds_count{job=\"$job\", status=~\"^2..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum ( increase(http_server_requests_seconds_count{job=\"$job\", status=~\"^4..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "4XX Errors Rate"
    },
    {
     "expr": "sum ( increase(http_server_requests_seconds_count{job=\"micronaut-monitoring\", status=~\"^5..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "5XX Errors Rate"
    }
   ]
  },
  {
   "title": "KTor-Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"ktor-monitoring\"}"
    }
   ]
  },
  {
   "title": "Micronaut-Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"micronaut-monitoring\"}"
    }
   ]
  },
  {
   "title": "Quarkus-Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"quarkus-java-monitoring\"}"
    }
   ]
  },
  {
   "title": "Spring-Boot-Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"spring-boot-monitoring\"}"
    }
   ]
  },
  {
   "title": "KTor-Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"ktor-monitoring\"}"
    }
   ]
  },
  {
   "title": "Micronaut-Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"micronaut-monitoring\"}"
    }
   ]
  },
  {
   "title": "Quarkus-Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"quarkus-java-monitoring\"}"
    }
   ]
  },
  {
   "title": "Spring-Boot-Up Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_uptime_seconds{job=\"spring-boot-monitoring\"}"
    }
   ]
  },
  {
   "title": "KTor-Http-Total-Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{job=\"$job\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "Total Request"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{job=\"$job\", status=~\"^2..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "2XX Success Rate"
    },
    {
     "expr": "sum (increase(ktor_http_server_requests_seconds_count{job=\"$job\", status=~\"^4..$\", route!=\"/metrics\"}[1m]))",
     "legendFormat": "4XX Client-Error Rate"
    }
   ]
  }
 ]
}